Repository Aurora2500/gsc, pull requests merged in 2020-07, with the labels that each got.

#5 Galaxy generation rng
  galaxy/Galaxy.gd
  project.godot
  solar_system/SolarSystem.gd
  solar_system/SolarSystem.tscn
  solar_system/star_link/StarLink.gd
  solar_system/star_link/StarLink.tscn
  solar_system/yellow.png
  solar_system/yellow.png.import
Labels: development

#8 Base save system for turning in game stuff into json.
  galaxy/Galaxy.gd
  galaxy/Galaxy.tscn
  galaxy/MainScene.tscn
  game_manager/GameManager.gd
  game_manager/MainScene.tscn
  project.godot
  solar_system/SolarSystem.gd
Labels: development

#10 Pause menu
  galaxy/SavePanel.gd
  galaxy/UI.gd
  game_management/MainScene.tscn
  project.godot
  user_interface/fonts/CarroisGothicSC-Regular.ttf
  user_interface/fonts/ConfirmPopup.gd
  user_interface/fonts/Montserrat-Bold.ttf
  user_interface/fonts/Montserrat-Regular.ttf
  user_interface/fonts/carrois-gothic-sc-regular.tres
  user_interface/fonts/montserrat-regular.tres
  user_interface/fonts/norwester.otf
  user_interface/fonts/norwester.tres
  user_interface/images/ui-corner-01.png
  user_interface/images/ui-corner-01.png.import
  user_interface/scenes/ConfirmPopup.tscn
  user_interface/scenes/ListItem.tscn
  user_interface/scenes/SaveScreen.tscn
  user_interface/styles/button_style.tres
  user_interface/styles/button_style_hover.tres
  user_interface/styles/button_style_pressed.tres
  user_interface/styles/lineedit_style.tres
  user_interface/styles/lineedit_style_focus.tres
  user_interface/styles/lineedit_style_readonly.tres
  user_interface/styles/panel_style.tres
  user_interface/themes/ListItemTheme.tres
  user_interface/themes/main_theme.tres
Labels: UI

#13 Merge final saving feature into develop
  solar_system/SolarSystem.gd
  user_interface/scenes/SaveScreen.tscn
  user_interface/scripts/SavePanel.gd
Labels: UI, development
